version: '2'
services:
  portal:
    image: node:12-slim
    tty: true
    stdin_open: true
    working_dir: /
    command: 'npm start'
    volumes:
      - ${PWD}:/app
  web:
    image: nginx
    links:
      - portal:portal
    ports:
     - "443:443"
    volumes:
      - ${PWD}/proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/${PORTAL_DOMAIN_NAME}.key:/certs/${PORTAL_DOMAIN_NAME}.key
      - ${PWD}/${PORTAL_DOMAIN_NAME}.crt:/certs/${PORTAL_DOMAIN_NAME}.crt
